# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdql < Formula
  desc "Schema-driven CRUD + FTS + wiki graph over markdown notes"
  homepage "https://github.com/notambourine/mdql"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.2/mdql_darwin_amd64.tar.gz"
      sha256 "c24e5719885ee9ce4a12b5da48f926a8efd22aef6b6d8a1d326b3ee845e62165"

      define_method(:install) do
        bin.install "mdql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.2/mdql_darwin_arm64.tar.gz"
      sha256 "92c07ffa767f5361c57e5ed816eb5f8f1e1192b4c8513de7a556665f74cc465b"

      define_method(:install) do
        bin.install "mdql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.2/mdql_linux_amd64.tar.gz"
      sha256 "e2a2663f90245b740d5a70bd7d6609194efe3d1c00b283a179009d0f178989e0"
      define_method(:install) do
        bin.install "mdql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.2/mdql_linux_arm64.tar.gz"
      sha256 "a133d621decdb22097ceb7415b496a534822634bf8d5b8072ba4792a1de88d06"
      define_method(:install) do
        bin.install "mdql"
      end
    end
  end

  test do
    assert_match "schema-driven", shell_output("#{bin}/mdql 2>&1")
  end
end
