# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdql < Formula
  desc "Schema-driven CRUD + FTS + wiki graph over markdown notes"
  homepage "https://github.com/notambourine/mdql"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.0/mdql_darwin_amd64.tar.gz"
      sha256 "aec76451709ee1daf42b71a1fc692b6f88e4b7dd3f4dcb8a97abebd78463b997"

      define_method(:install) do
        bin.install "mdql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.0/mdql_darwin_arm64.tar.gz"
      sha256 "4490234d8e45842c9300057e89fece727dd2a1e6575da8baa7dc0356b41c4efd"

      define_method(:install) do
        bin.install "mdql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.0/mdql_linux_amd64.tar.gz"
      sha256 "0dcc62c98bdc6b93e6f1b51297ba7f5cfea38ed5c0c9293ab1345447d3b8008e"
      define_method(:install) do
        bin.install "mdql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.0/mdql_linux_arm64.tar.gz"
      sha256 "8eb33471d05e7196381b7f39c4d5c62838dcad9e4e2fa724a6570895a5090f48"
      define_method(:install) do
        bin.install "mdql"
      end
    end
  end

  test do
    assert_match "schema-driven", shell_output("#{bin}/mdql 2>&1")
  end
end
