# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdql < Formula
  desc "Schema-driven CRUD + FTS + wiki graph over markdown notes"
  homepage "https://github.com/notambourine/mdql"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.1/mdql_darwin_amd64.tar.gz"
      sha256 "447642b483553f40fd674e02186ffc89be01d21015e5f336a6959c757c6531e0"

      define_method(:install) do
        bin.install "mdql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.1/mdql_darwin_arm64.tar.gz"
      sha256 "232a8094e9ec11cee7e0e4c21235c50f65bad07ca7037e20a809250039870d29"

      define_method(:install) do
        bin.install "mdql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.1/mdql_linux_amd64.tar.gz"
      sha256 "8a31fcaa594a6cae8740ebab8437aae4c0c13a0adcadd84204434e9da07908af"
      define_method(:install) do
        bin.install "mdql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/notambourine/mdql/releases/download/v0.1.1/mdql_linux_arm64.tar.gz"
      sha256 "d676b246f15ddaace7cbffc60695eb50822d6964dacf301d40f5e0eae3521a26"
      define_method(:install) do
        bin.install "mdql"
      end
    end
  end

  test do
    assert_match "schema-driven", shell_output("#{bin}/mdql 2>&1")
  end
end
